# Generated by Django 4.1.3 on 2022-12-21 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reminder_reminder_time_task_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_join_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
