# Generated by Django 4.1.3 on 2022-12-21 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_user_join_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
