# Generated by Django 4.1.3 on 2022-12-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reminder_reminder_task_task_task_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_reminder',
        ),
    ]
