# Generated by Django 4.1.3 on 2022-12-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_reminder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reminder'),
        ),
    ]
