# Generated by Django 4.1.3 on 2022-12-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_task_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_reminder',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
            preserve_default=False,
        ),
    ]
