# Generated by Django 4.1.3 on 2022-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_task_task_reminder_reminder_reminder_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_vibrate',
            field=models.BooleanField(default=True),
        ),
    ]
