# Generated by Django 4.1.3 on 2022-12-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_task_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
