# Generated by Django 4.1.3 on 2022-12-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_reminder_reminder_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
