# Generated by Django 4.1.3 on 2022-12-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reminder_reminder_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_reminder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reminder'),
        ),
    ]
